"""First Migration

Revision ID: e6212ba327d6
Revises: 
Create Date: 2026-07-16 00:32:41.342670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6212ba327d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('price_for_meter', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=220), nullable=False),
    sa.Column('last_name', sa.String(length=220), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('switching', sa.Boolean(), nullable=False),
    sa.Column('notification', sa.Enum('Me', 'Me_And_Agent', 'Agent', 'Off', name='notificationchoice', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advantages',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('advantage_1', sa.Boolean(), nullable=False),
    sa.Column('advantage_2', sa.Boolean(), nullable=False),
    sa.Column('advantage_3', sa.Boolean(), nullable=False),
    sa.Column('advantage_4', sa.Boolean(), nullable=False),
    sa.Column('advantage_5', sa.Boolean(), nullable=False),
    sa.Column('advantage_6', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id')
    )
    op.create_table('apartment_images',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('display_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id', 'image_id')
    )
    op.create_table('communication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('gas', sa.Boolean(), nullable=False),
    sa.Column('electricity', sa.Boolean(), nullable=False),
    sa.Column('sewage', sa.Boolean(), nullable=False),
    sa.Column('water', sa.Boolean(), nullable=False),
    sa.Column('heating', sa.Enum('Nope', 'Central', 'Private', name='househeatingchoice', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_apartment',
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=220), nullable=True),
    sa.Column('adress', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('number_of_rooms', sa.String(length=220), nullable=False),
    sa.Column('layout', sa.String(length=220), nullable=True),
    sa.Column('kitchen_area', sa.Float(), nullable=False),
    sa.Column('heating_type', sa.Enum('Gas', 'Electricity', name='heatingtypechoice', native_enum=False), nullable=False),
    sa.Column('balcony', sa.Boolean(), nullable=False),
    sa.Column('mortgage', sa.Boolean(), nullable=False),
    sa.Column('agent_commission', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=220), nullable=False),
    sa.Column('communication', sa.Enum('Call', 'Message', 'Call_And_Message', name='communicationchoice', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apartment_id')
    )
    op.create_table('favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('apartment_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'apartment_id')
    )
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price_for_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price_for_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_area', sa.Float(), nullable=False),
    sa.Column('max_area', sa.Float(), nullable=False),
    sa.Column('repair', sa.Enum('Non', 'Rough', 'Full_fledged', name='repairuserchoice', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_corps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Economy', 'Middle', 'Elite', name='houseclasschoice', native_enum=False), nullable=False),
    sa.Column('house_type', sa.Boolean(), nullable=False),
    sa.Column('construction_technique', sa.Text(), nullable=False),
    sa.Column('territory', sa.Boolean(), nullable=False),
    sa.Column('distance_to_sea', sa.String(), nullable=True),
    sa.Column('ceiling_height', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('house_id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('variants', sa.String(length=220), nullable=False),
    sa.Column('sums', sa.Boolean(), nullable=False),
    sa.Column('house_status', sa.Enum('Commercial', 'Residential', name='houseregisterchoice', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('user_images',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('display_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'image_id')
    )
    op.create_table('calculation_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corps_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['corps_id'], ['house_corps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_storey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['house_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_storey')
    op.drop_table('house_section')
    op.drop_table('calculation_variant')
    op.drop_table('user_images')
    op.drop_table('subscription')
    op.drop_table('registration')
    op.drop_table('news')
    op.drop_table('infrastructure')
    op.drop_table('house_corps')
    op.drop_table('filter')
    op.drop_table('favorite')
    op.drop_table('detail_apartment')
    op.drop_table('communication')
    op.drop_table('apartment_images')
    op.drop_table('advantages')
    op.drop_table('user')
    op.drop_table('image')
    op.drop_table('house')
    op.drop_table('apartment')
    # ### end Alembic commands ###
